language: objective-c
osx_image: xcode8.1
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install slather --no-ri --no-rdoc
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace TLDR.xcworkspace -scheme TLDR -destination 'platform=iOS Simulator,name=iPhone 6s' build | xcpretty
