# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6s"
  # "iPhone 6 Plus",
  # "iPhone 5",
  # "iPhone 4s",
  # "iPad Retina",
  # "iPad Pro"
 ])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "TLDR"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./TLDR.xcworkspace"

# For more information about all available options run
# snapshot --help
