name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Xcode Tests
    runs-on: macos-latest

    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: xcodebuild test -project TLDR.xcodeproj -scheme TLDR -destination 'platform=iOS Simulator,name=iPhone 16'